# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d742ace81ae8423a85e994ab0d31e39"
name = "Ch-product"
handle = "ch-product"
application_url = "https://wars-detected-theories-u.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://wars-detected-theories-u.trycloudflare.com/auth/callback", "https://wars-detected-theories-u.trycloudflare.com/auth/shopify/callback", "https://wars-detected-theories-u.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
